






export const UPDATE_MAPCLICK_COORDINATES = 'UPDATE_MAPCLICK_COORDINATES';
export const UPDATE_CENTERPOINT_COORDINATES = 'UPDATE_CENTERPOINT_COORDINATES';
export const SET_CONFIG = 'SET_CONFIG';
export const FETCH_DATA = 'fetch_data';
